"""
URLs for the tool in maintenance mode.  Every URL directs the user to the
maintenance view.
"""

from django.conf.urls import url, patterns
from django.contrib.auth import views as auth_views
from BoMConfig import views

urlpatterns = patterns(
    '',
    url(r'^$', views.Maintenance, name='index'),
    url(r'^entry/$', views.Maintenance, name='entry'),
    url(r'^entry/header/$', views.Maintenance,
        {'sTemplate': 'BoMConfig/configheader.html'}, name='configheader'),
    url(r'^entry/config/$', views.Maintenance, name='config'),
    url(r'^entry/toc/$', views.Maintenance, name='configtoc'),
    url(r'^entry/revision/$', views.Maintenance, name='configrevision'),
    url(r'^entry/inquiry/$', views.Maintenance, {'inquiry': True},
        name='configinquiry'),
    url(r'^entry/sitetemplate/$', views.Maintenance, {'inquiry': False},
        name='configsite'),
    url(r'^entry/clone/$', views.Maintenance, name='configclone'),
    url(r'^search/$', views.Maintenance, name='search'),
    url(r'^search/adv/$', views.Maintenance, {'advanced': True},
        name='searchadv'),
    url(r'^pricing/$', views.Maintenance, name='pricing'),
    url(r'^pricing/download/$', views.Maintenance, name='pricingdownload'),
    url(r'^pricing_config/$', views.Maintenance, name='configpricing'),
    url(r'^pricing_config/download/$', views.Maintenance,
        name='configpricingdownload'),
    url(r'^pricing_report/$', views.Maintenance, name='basepricing'),
    url(r'^pricing_report/download/$', views.Maintenance,
        name='pricingoverviewdownload'),
    url(r'^pricing_erosion/$', views.Maintenance, name='erosionpricing'),
    url(r'^pricing_erosion/search/$', views.Maintenance, name='erosionajax'),
    url(r'^pricing_erosion/download/$', views.Maintenance,
        name='erosiondownload'),
    url(r'^reporting/$', views.Maintenance, name='reporting'),
    url(r'^approvals/$', views.Maintenance, name='approval'),
    url(r'^actions/$', views.Maintenance, name='action'),
    url(r'^actions/inprocess/$', views.Maintenance, {'type':'inprocess'},
        name='action_inprocess'),
    url(r'^actions/active/$', views.Maintenance, {'type':'active'},
        name='action_active'),
    url(r'^actions/hold/$', views.Maintenance, {'type':'hold'},
        name='action_hold'),
    url(r'^actions/changepart/$', views.Maintenance, {'type': 'changepart'},
        name='action_changepart'),
    url(r'^actions/changepart/post/$', views.Maintenance,
        name='action_changepart_post'),
    url(r'^login/$', views.Login, name='login'),
    url(r'^validate/$', views.Maintenance, name='validator'),
    url(r'^download/$', views.Maintenance, name='download'),
    url(r'^downloadmulti/$', views.Maintenance, name='downloadmulti'),
    url(r'^downloadresult/$', views.Maintenance, name='downloadresult'),
    url(r'^reactsearch/$', views.Maintenance, name='reactsearch'),
    url(r'^upload/$', views.Maintenance, name='upload'),
    url(r'^baseline/$', views.Maintenance, name='baseline'),
    url(r'^baseload/$', views.Maintenance, name='baseload'),
    url(r'^baselinedwnld/$', views.Maintenance, name='baselinedownload'),
    url(r'^baselinemasterdwnld/$', views.Maintenance,
        name='baselinemasterdownload'),
    url(r'^baselinerollback/$', views.Maintenance, name='baselinerollback'),
    url(r'^baselinerollbackcheck/$', views.Maintenance,
        name='baselinerollbacktest'),
    url(r'^document/$', views.Maintenance, name='document_create'),
    url(r'^unlock/$', views.Maintenance, name='finalunlock'),
    url(r'^lock/$', views.Maintenance, name='initlock'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^list_fill/$', views.Maintenance, name='list_fill'),
    url(r'^list_react_fill/$', views.Maintenance, name='list_react_fill'),
    url(r'^approve/$', views.Maintenance, name='approve'),
    url(r'^approval_data/$', views.Maintenance, name='approve_info'),
    url(r'^approval_list/$', views.Maintenance, name='approve_list'),
    url(r'^password_change/$', auth_views.password_change,
        {'post_change_redirect': 'bomconfig:index'}, name='change_password'),
    url(r'^admin/mailing/$', views.Maintenance, name='mailadmin'),
    url(r'^admin/mailing/change/(?P<iRecordId>\d+)/$', views.Maintenance,
        name='mailchange'),
    url(r'^admin/mailing/add/$', views.Maintenance, name='mailadd'),
    url(r'^admin/user/$', views.Maintenance, name='useradmin'),
    url(r'^admin/user/add/$', views.Maintenance, name='useradd'),
    url(r'^admin/user/changeuser/(?P<iUserId>\d+)/$', views.Maintenance,
        name='userchange'),
    url(r'^admin/$', views.Maintenance, name='adminlanding'),
    url(r'^admin/approval/$', views.Maintenance, name='approvaladmin'),
    url(r'^admin/approval/add/$', views.Maintenance, name='approvaladd'),
    url(r'^admin/approval/change/(?P<iObjId>\d+)/$', views.Maintenance,
        name='approvalchange'),
    url(r'^customer_audit/$', views.Maintenance, name='customerauditland'),
    url(r'^customer_audit/audit/$', views.Maintenance, name='customeraudit'),
    url(r'^customer_audit/validate/$', views.Maintenance,
        name='audit_validate'),
    url(r'^customer_audit/upload/$', views.Maintenance,
        name='customerauditupload'),
)
